# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-vcs-permalinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      # Using this instead of a packaged eslint check because it's trivial.
      - id: eslint
        name: Run `eslint`
        language: system
        types: [ts]
        entry: eslint
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
